In [47]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf

In [48]:
train_data = pd.read_csv('E:\VIL Confidential Information Dataset\Train_cleaned.csv')
test_data = pd.read_csv('E:\VIL Confidential Information Dataset\Test_cleaned.csv')

In [49]:
train_data

,Age,ARPU,Age on Network,Brand Identifier,Circle Name,Connection Type,Data Usage,Gender,Genre,International Usage,Recharge,SMS Usage,VAS Subscription,Voice Usage,Web/App,DND
0,1,1,2,1,2,1,2,1,2,0,6,6,43,5,1,0
1,4,1,6,1,2,1,6,1,3,0,3,1,87,7,1,0
2,2,2,7,0,0,1,2,1,3,0,2,1,87,8,1,1
3,9,7,1,1,3,1,7,0,2,1,4,1,87,5,1,1
4,9,4,3,1,2,0,2,3,3,0,-1,3,43,5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112584,4,3,1,1,3,1,7,1,3,0,5,1,87,4,1,0
112585,0,2,7,0,0,1,2,0,3,0,2,6,87,7,0,1
112586,9,1,3,0,1,1,3,1,4,0,3,0,87,0,0,0
112587,4,2,1,1,2,1,7,1,0,0,1,1,25,8,1,0
112588,2,4,2,1,3,0,2,0,2,0,-1,1,87,1,2,0

In [50]:
test_data

,Age,ARPU,Age on Network,Brand Identifier,Circle Name,Connection Type,Data Usage,Gender,Genre,International Usage,Recharge,SMS Usage,VAS Subscription,Voice Usage,Web/App,DND
0,9,1,2,1,2,1,6,1,3,0,1,1,87,1,1,0
1,4,2,1,1,2,1,2,0,3,0,3,1,85,2,1,0
2,4,5,7,0,1,0,5,1,2,0,-1,1,87,8,0,0
3,4,7,4,0,1,0,3,1,2,0,-1,0,87,2,0,0
4,9,7,7,0,1,0,2,1,2,0,-1,1,87,8,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48237,9,1,6,1,2,1,6,0,2,0,0,1,25,6,1,0
48238,4,2,5,1,2,1,7,1,3,0,0,1,29,4,1,0
48239,2,3,4,1,2,1,1,1,2,0,0,1,87,2,1,0
48240,6,1,6,1,2,1,1,1,2,0,3,1,75,2,1,0
48241,1,3,2,1,2,1,1,0,0,0,3,1,23,2,1,0

In [51]:
from xgboost import XGBClassifier

In [52]:
X = train_data.iloc[:,[0,1,2,3,4,5,6,7,8,9,11,12,13,14,15]].values
y = train_data.iloc[:,10:11].values

a = test_data.iloc[:,[0,1,2,3,4,5,6,7,8,9,11,12,13,14,15]].values
b = test_data.iloc[:,10:11].values

In [38]:
from sklearn.model_selection import train_test_split

In [29]:
model = XGBClassifier()
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [30]:
y_pred = model.predict(a)
predictions = [round(value) for value in y_pred]
accuracy = accuracy_score(b, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 55.69%

In [53]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
a = sc.transform(a)

In [40]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(a)

In [41]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(b, y_pred)

In [42]:
acc*100

52.267733510219315

In [54]:
# Encoding categorical data
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()

In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

e:\py-env\customdash\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [59]:
max(y)

11

In [60]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 512, init = 'uniform', activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 256, init = 'uniform', activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 32, init = 'uniform', activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 16, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 12, init = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X, y, batch_size = 32, nb_epoch = 50)

e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=512, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=256, kernel_initializer="uniform")`
  del sys.path[0]
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  app.launch_new_instance()
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:19: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=64, kernel_initializer="uniform")`
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:22: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=32, kernel_initializer="uniform")`
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:25: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=16, kernel_initializer="uniform")`
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:28: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=12, kernel_initializer="uniform")`
e:\py-env\customdash\lib\site-packages\ipykernel_launcher.py:34: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

Epoch 1/50
112589/112589 [==============================] - 13s 112us/step - loss: 1.2844 - accuracy: 0.4965
Epoch 2/50
112589/112589 [==============================] - 12s 110us/step - loss: 1.1338 - accuracy: 0.5513
Epoch 3/50
112589/112589 [==============================] - 12s 111us/step - loss: 1.1097 - accuracy: 0.5624
Epoch 4/50
112589/112589 [==============================] - 12s 110us/step - loss: 1.0969 - accuracy: 0.5660
Epoch 5/50
112589/112589 [==============================] - 12s 110us/step - loss: 1.0880 - accuracy: 0.5668
Epoch 6/50
112589/112589 [==============================] - 13s 111us/step - loss: 1.0816 - accuracy: 0.5694
Epoch 7/50
112589/112589 [==============================] - 13s 112us/step - loss: 1.0753 - accuracy: 0.5721
Epoch 8/50
112589/112589 [==============================] - 13s 112us/step - loss: 1.0682 - accuracy: 0.5737
Epoch 9/50
112589/112589 [==============================] - 12s 111us/step - loss: 1.0621 - accuracy: 0.5761
Epoch 10/50
112589/112589 [==============================] - 14s 122us/step - loss: 1.0556 - accuracy: 0.5790
Epoch 11/50
112589/112589 [==============================] - 12s 106us/step - loss: 1.0470 - accuracy: 0.5820
Epoch 12/50
112589/112589 [==============================] - 12s 106us/step - loss: 1.0405 - accuracy: 0.5843
Epoch 13/50
112589/112589 [==============================] - 12s 105us/step - loss: 1.0298 - accuracy: 0.5884
Epoch 14/50
112589/112589 [==============================] - 12s 103us/step - loss: 1.0221 - accuracy: 0.5910
Epoch 15/50
112589/112589 [==============================] - 12s 103us/step - loss: 1.0135 - accuracy: 0.5948
Epoch 16/50
112589/112589 [==============================] - 12s 103us/step - loss: 1.0036 - accuracy: 0.5990
Epoch 17/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9928 - accuracy: 0.6037
Epoch 18/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9816 - accuracy: 0.6079
Epoch 19/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.9717 - accuracy: 0.6120
Epoch 20/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.9593 - accuracy: 0.6177
Epoch 21/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9482 - accuracy: 0.6211
Epoch 22/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9384 - accuracy: 0.6251
Epoch 23/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9254 - accuracy: 0.6305
Epoch 24/50
112589/112589 [==============================] - 12s 103us/step - loss: 0.9155 - accuracy: 0.6353
Epoch 25/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.9048 - accuracy: 0.6389
Epoch 26/50
112589/112589 [==============================] - 12s 108us/step - loss: 0.8941 - accuracy: 0.6435
Epoch 27/50
112589/112589 [==============================] - 12s 107us/step - loss: 0.8836 - accuracy: 0.6477
Epoch 28/50
112589/112589 [==============================] - 14s 124us/step - loss: 0.8719 - accuracy: 0.6518
Epoch 29/50
112589/112589 [==============================] - 11s 99us/step - loss: 0.8625 - accuracy: 0.6552
Epoch 30/50
112589/112589 [==============================] - 13s 116us/step - loss: 0.8545 - accuracy: 0.6582
Epoch 31/50
112589/112589 [==============================] - 14s 124us/step - loss: 0.8494 - accuracy: 0.6621
Epoch 32/50
112589/112589 [==============================] - 15s 129us/step - loss: 0.8349 - accuracy: 0.6679
Epoch 33/50
112589/112589 [==============================] - 12s 107us/step - loss: 0.8274 - accuracy: 0.6697
Epoch 34/50
112589/112589 [==============================] - 12s 105us/step - loss: 0.8179 - accuracy: 0.6729
Epoch 35/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.8098 - accuracy: 0.6782
Epoch 36/50
112589/112589 [==============================] - 12s 105us/step - loss: 0.8022 - accuracy: 0.6800
Epoch 37/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7945 - accuracy: 0.6837
Epoch 38/50
112589/112589 [==============================] - 12s 106us/step - loss: 0.7876 - accuracy: 0.6853
Epoch 39/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7814 - accuracy: 0.6904
Epoch 40/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7698 - accuracy: 0.6941
Epoch 41/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7638 - accuracy: 0.6968
Epoch 42/50
112589/112589 [==============================] - 12s 107us/step - loss: 0.7643 - accuracy: 0.6978
Epoch 43/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7521 - accuracy: 0.7007
Epoch 44/50
112589/112589 [==============================] - 12s 108us/step - loss: 0.7411 - accuracy: 0.7042
Epoch 45/50
112589/112589 [==============================] - 12s 106us/step - loss: 0.7388 - accuracy: 0.7047
Epoch 46/50
112589/112589 [==============================] - 12s 105us/step - loss: 0.7339 - accuracy: 0.7092
Epoch 47/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7256 - accuracy: 0.7112
Epoch 48/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7205 - accuracy: 0.7137
Epoch 49/50
112589/112589 [==============================] - 12s 104us/step - loss: 0.7148 - accuracy: 0.7156
Epoch 50/50
112589/112589 [==============================] - 12s 110us/step - loss: 0.7099 - accuracy: 0.7175

In [61]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
b = le1.fit_transform(b)

e:\py-env\customdash\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [64]:
max(b)

11

In [68]:
from sklearn.preprocessing import OneHotEncoder
onehotencoderr = OneHotEncoder()
a = onehotencoderr.fit_transform(a).toarray()

In [66]:
a = test_data.iloc[:,[0,1,2,3,4,5,6,7,8,9,11,12,13,14,15]].values

In [69]:
a.shape

(48242, 171)